# 1.1 Creating a Vector
## Problem


*   You need to create a vector


In [1]:
# Solution : Use NumPy to create a one-dimensional array:

# Load library
import numpy as np

# Create a vector as a row
vector_row = np.array([1, 2, 3])

# Create a vector as a column
vector_column = np.array([[1],
[2],
[3]])

print(vector_column)

[[1]
 [2]
 [3]]


# Creating a Matrix
## Problem
*  You need to create a matrix.

In [3]:
# Solution : Use NumPy to create a two-dimensional array

# Create a matrix
matrix = np.array([[1, 2],
[1, 2],
[1, 2]])
print(matrix)

[[1 2]
 [1 2]
 [1 2]]


# Creating a Sparse Matrix
## Problem
*  Given data with very few nonzero values, you want to efficiently represent it.
*  Use scipy.sparse library
* See below link for more info:
*  [Sparse matrices, SciPy documentation](https://docs.scipy.org/doc/scipy/reference/sparse.html)
*  [101 Ways to Store a Sparse Matrix](https://https://medium.com/@jmaxg3/101-ways-to-store-a-sparse-matrix-c7f2bf15a229)  

In [5]:
#  Solution
#  Create a sparse matrix:
from scipy import sparse

# Create a matrix
matrix = np.array([[0, 0],
[0, 1],
[3, 0]])

# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [7]:
#Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
[3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)

# View original sparse matrix
print(matrix_sparse)
# (1, 1) 1
# (2, 0) 3

# View larger sparse matrix
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3
  (1, 1)	1
  (2, 0)	3


# Selecting Elements
## Problem

*   You need to select one or more elements in a vector or matrix.


In [21]:
#Solution
#NumPy’s arrays make that easy:

# Load library
import numpy as np

# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

# Select third element of vector
print(vector[2])
#3

# Select second row, second column
print(matrix[1,1])
#5

3
5


In [27]:
#Select all elements of a vector
print(vector[:])
#array([1, 2, 3, 4, 5, 6])

# Select everything up to and including the third element
print(vector[:3])
# array([1, 2, 3])

# Select everything after the third element
print(vector[3:])
# array([4, 5, 6])

# Select the last element
print(vector[-1])
# 6

# Select the first two rows and all columns of a matrix
print(matrix[:2,:])
#array([[1, 2, 3],
#       [4, 5, 6]])

# Select all rows and the second column
print(matrix[:,1:2])
#array([[2],
#       [5],
#       [8]]

[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
6
[[1 2 3]
 [4 5 6]]
[[2]
 [5]
 [8]]


# Describing a Matrix
## Problem
*  You want to describe the shape, size, and dimensions of the matrix.

In [29]:
# Solution
# Use shape, size, and ndim:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

# View number of rows and columns
print(matrix.shape)
#(3, 4)

# View number of elements (rows * columns)
print(matrix.size)
#12

# View number of dimensions
print(matrix.ndim)

(3, 4)
12
2


# Applying Operations to Elements
## Problem
*  You want to apply some function to multiple elements in an array.

In [30]:
#Solution
#Use NumPy’s vectorize:

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

# Create function that adds 100 to something
add_100 = lambda i: i + 100

# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)

# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [31]:
# Add 100 to all elements
matrix + 100

#array([[101, 102, 103],
#[104, 105, 106],
#[107, 108, 109]])

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

# Finding the Maximum and Minimum Values
## Problem
*  You need to find the maximum or minimum value in an array.

In [33]:
#Solution
#Use NumPy’s max and min:

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

# Return maximum element
print(np.max(matrix))
#9

# Return minimum element
print(np.min(matrix))

9
1


# Calculating the Average, Variance, and Standard Deviation
## Problem
*  You want to calculate some descriptive statistics about an array.

In [35]:
# Solution
# Use NumPy’s mean, var, and std:

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

# Return mean
print(np.mean(matrix))
#5.0

# Return variance
print(np.var(matrix))
#6.666666666666667

# Return standard deviation
print(np.std(matrix))
#2.5819888974716112

5.0
6.666666666666667
2.581988897471611


# Reshaping Arrays
## Problem
*  You want to change the shape (number of rows and columns) of an array without
changing the element values.

In [37]:
# Solution
# Use NumPy’s reshape:

# Load library
import numpy as np

# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9],
[10, 11, 12]])

# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)
#array([[ 1, 2, 3, 4, 5, 6],
#[ 7, 8, 9, 10, 11, 12]])
#1.9

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

# Transposing a Vector or Matrix
## Problem
*  You need to transpose a vector or matrix.

In [38]:
# Solution
# Use the T method:

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Flattening a Matrix
## Problem
*  You need to transform a matrix into a one-dimensional array.

In [39]:
# Solution
# Use flatten:

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Finding the Rank of a Matrix
## Problem
*  You need to know the rank of a matrix.
*  [The Rank of a Matrix, CliffsNotes](https://https://www.cliffsnotes.com/study-guides/algebra/linear-algebra/real-euclidean-vector-spaces/the-rank-of-a-matrix)

In [40]:
# Solution
# Use NumPy’s linear algebra method matrix_rank:

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 1, 1],
[1, 1, 10],
[1, 1, 15]])

# Return matrix rank
np.linalg.matrix_rank(matrix)

2

# Calculating the Determinant
## Problem
*  You need to know the determinant of a matrix.
*  [The determinant | Essence of linear algebra, chapter 5, 3Blue1Brown](https://https://www.youtube.com/watch?v=Ip3X9LOh2dk)
*  [Determinant, Wolfram MathWorld](https://https://mathworld.wolfram.com/Determinant.html)

In [41]:
# Solution
# Use NumPy’s linear algebra method det:

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
[2, 4, 6],
[3, 8, 9]])

# Return determinant of matrix
np.linalg.det(matrix)

0.0

# Getting the Diagonal of a Matrix
## Problem
*  You need to get the diagonal elements of a matrix.

In [42]:
#Solution
#Use diagonal:

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
[2, 4, 6],
[3, 8, 9]])

# Return diagonal elements
matrix.diagonal()

array([1, 4, 9])

# Calculating the Trace of a Matrix
## Problem
*  You need to calculate the trace of a matrix.
*  [The Trace of a Square Matrix](http://mathonline.wikidot.com/the-trace-of-a-square-matrix)

In [43]:
# Solution
#Use trace:

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
[2, 4, 6],
[3, 8, 9]])

# Return trace
matrix.trace()

14

# Finding Eigenvalues and Eigenvectors
## Problem
*  You need to find the eigenvalues and eigenvectors of a square matrix.
*  [Eigenvectors and Eigenvalues Explained Visually, Setosa.io](https://https://setosa.io/ev/eigenvectors-and-eigenvalues/)  
*  [Eigenvectors and eigenvalues | Essence of linear algebra, Chapter 10,
3Blue1Brown](https://https://www.youtube.com/watch?v=PFDu9oVAE-g) 

In [45]:
# Solution
# Use NumPy’s linalg.eig:

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, -1, 3],
[1, 1, 6],
[3, 8, 9]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# View eigenvalues
print(eigenvalues)
#array([ 13.55075847, 0.74003145, -3.29078992])

# View eigenvectors
print(eigenvectors)

[13.55075847  0.74003145 -3.29078992]
[[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


# Calculating Dot Products
## Problem
*  You need to calculate the dot product of two vectors.

In [46]:
# Solution
# Use NumPy’s dot:

# Load library
import numpy as np

# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# Calculate dot product
np.dot(vector_a, vector_b)

32

# Adding and Subtracting Matrices
## Problem
*  You want to add or subtract two matrices.
*  [Vector dot product and vector length, Khan Academy](https://www.khanacademy.org/math/linear-algebra/vectors-and-spaces/dot-cross-products/v/vector-dot-product-and-vector-length)
*  [Dot Product, Paul’s Online Math Notes](https://https://tutorial.math.lamar.edu/Classes/CalcII/DotProduct.aspx)

In [48]:
# Solution
# Use NumPy’s add and subtract:

# Load library
import numpy as np

# Create matrix
matrix_a = np.array([[1, 1, 1],
[1, 1, 1],
[1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
[1, 3, 1],
[1, 3, 8]])

# Add two matrices
np.add(matrix_a, matrix_b)
# array([[ 2, 4, 2],
# [ 2, 4, 2],
# [ 2, 4, 10]])

# Subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

# Multiplying Matrices
## Problem
*  You want to multiply two matrices.
*  [Array vs. Matrix Operations, MathWorks](https://https://www.mathworks.com/help/matlab/matlab_prog/array-vs-matrix-operations.html?requestedDomain=true)

In [50]:
# Solution
# Use NumPy’s dot:

# Load library
import numpy as np

# Create matrix
matrix_a = np.array([[1, 1],
[1, 2]])

# Create matrix
matrix_b = np.array([[1, 3],
[1, 2]])

# Multiply two matrices
print(np.dot(matrix_a, matrix_b))

# Multiply two matrices
print(matrix_a @ matrix_b)

[[2 5]
 [3 7]]
[[2 5]
 [3 7]]


# Inverting a Matrix
## Problem
*  You want to calculate the inverse of a square matrix.
*  [Inverse of a Matrix](http://www.mathwords.com/i/inverse_of_a_matrix.htm)

In [51]:
#Solution
#Use NumPy’s linear algebra inv method:

# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 4],
[2, 5]])

# Calculate inverse of matrix
print(np.linalg.inv(matrix))

[[-1.66666667  1.33333333]
 [ 0.66666667 -0.33333333]]


# Generating Random Values
## Problem
*  You want to generate pseudorandom values.

In [56]:
# Solution
#Use NumPy’s random:

# Load library
import numpy as np

# Set seed
print(np.random.seed(0))

# Generate three random floats between 0.0 and 1.0
print(np.random.random(3))

# Generate three random integers between 1 and 10
print(np.random.randint(0, 11, 3))

# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
print(np.random.normal(0.0, 1.0, 3))

#array([-1.42232584, 1.52006949, -0.29139398])

# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
print(np.random.logistic(0.0, 1.0, 3))

#array([-0.98118713, -0.08939902, 1.46416405])

# Draw three numbers greater than or equal to 1.0 and less than 2.0
print(np.random.uniform(1.0, 2.0, 3))

#array([ 1.47997717, 1.3927848 , 1.83607876])

None
[0.5488135  0.71518937 0.60276338]
[3 7 9]
[-1.42232584  1.52006949 -0.29139398]
[-0.98118713 -0.08939902  1.46416405]
[1.47997717 1.3927848  1.83607876]
